#!/bin/bash
#Script to delete an ACTIVE user in Debian. Requires Sudo priviledges.

#Colours for printing text
RED='\033[0;31m'
PRPL='\033[0;35m'
GRN='\033[0;32m'
NORM='\033[0m'

USERS=$(users)
ME=$(whoami)
TARGET=""

echo -e "${RED}Delete active user.${NORM}"
echo "Cannot delete: $ME or root."
while [[ *" $TARGET "* != " $USERS " || -z $TARGET  ]]; do
	echo -e "Currently logged in: ${PRPL}$USERS${NORM}"
	echo -e "Write ${PRPL}exit${NORM} to exit."
	echo -n "Which user do you want to delete?: "
	read TARGET
	if [ -z $TARGET ]; then
		continue
	fi
	case "${TARGET}" in
		${ME}) echo -e "${RED}$ME is currently logged in user, cannot delete.${NORM}"
		;;
		"root") echo -e "${RED}Cannot delete root.${NORM}"
		;;
		"exit") exit 1
		;;
		*) if echo $USERS | grep -w $TARGET > /dev/null; then
			echo "$TARGET will be deleted"
			sudo userdel -rf $TARGET
			echo "$TARGET has been deleted, good riddance."
			exit 0
		else
			echo "$TARGET not in list"
		fi
		;;
	esac
	echo ""
done
